# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    ssh_known_hosts:
      - coldfs.ru

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Creating Build tarball
          command: |
            mkdir /tmp/artifacts;
            tar --exclude=".git"  --exclude='.circleci' -czvf /tmp/artifacts/build-$CIRCLE_BUILD_NUM.tar.gz .
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/artifacts/build-$CIRCLE_BUILD_NUM.tar.gz cold@coldfs.ru:/data/builds/
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t cold@coldfs.ru "/data/projects/deploydok/deplodok.sh --project=gp --build=$CIRCLE_BUILD_NUM"

#            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t cold@coldfs.ru "mkdir /data/builds/gp-$CIRCLE_BUILD_NUM; tar -zxvf /data/builds/$CIRCLE_PROJECT_REPONAME-build-$CIRCLE_BUILD_NUM.tar.gz -C /data/builds/gp-$CIRCLE_BUILD_NUM"
#            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t cold@coldfs.ru "rm /data/builds/$CIRCLE_PROJECT_REPONAME-build-$CIRCLE_BUILD_NUM.tar.gz"

